/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Inquiry = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const QuotationRequest = IDL.Record({
  'service' : IDL.Text,
  'orgType' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'email' : IDL.Text,
  'timestamp' : Time,
  'organization' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'getAllSubmissions' : IDL.Func([], [IDL.Vec(QuotationRequest)], ['query']),
  'submitInquiry' : IDL.Func([Inquiry], [], []),
  'submitQuotation' : IDL.Func([QuotationRequest], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Inquiry = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const QuotationRequest = IDL.Record({
    'service' : IDL.Text,
    'orgType' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'email' : IDL.Text,
    'timestamp' : Time,
    'organization' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'getAllSubmissions' : IDL.Func([], [IDL.Vec(QuotationRequest)], ['query']),
    'submitInquiry' : IDL.Func([Inquiry], [], []),
    'submitQuotation' : IDL.Func([QuotationRequest], [], []),
  });
};

export const init = ({ IDL }) => { return []; };